# 3. Demonstrate use of List 
l = [10, 20, 30, 40, 50, 5,15]
print("First item:", l[0])
print("Length:", len(l))
print("Count of 20:", l.count(20))
print("Slice from index 1 to 4:", l[1:5])
print("Slice from beginning to index 3:", l[:4])
l.append(60)
print("Append 60:", l)
l.insert(2, 25)
print("Insert 25 at index 2:", l)
l.remove(30)
print("Remove 30:", l)
print("Pop last item", l.pop())
print("After pop:", l)
l.sort()
print("Sorted:", l)
l.reverse()
print("Reversed:", l)
l.clear()
print("Cleared:", l)